//! # autopack-dockerfile
//!
//! Lowers a [`BuildPlan`] into a BuildKit Dockerfile.
//!
//! A Dockerfile is not the most expressive target for a plan — BuildKit's LLB
//! can execute independent steps concurrently, which a linear Dockerfile
//! cannot express as precisely. It is, however, the target that runs
//! *everywhere*: `docker build`, `buildx`, `buildctl`, Kaniko, Depot, and every
//! CI system already understand it, with no daemon-side plugin to install.
//!
//! Plan features map onto BuildKit as follows:
//!
//! | Plan concept    | Dockerfile                              |
//! |-----------------|-----------------------------------------|
//! | step            | a named build stage                     |
//! | first input     | `FROM`                                  |
//! | other inputs    | `COPY --from=`                          |
//! | cache           | `RUN --mount=type=cache`                |
//! | secret          | `RUN --mount=type=secret,env=`          |
//! | asset + file cmd| `COPY <<EOF` heredoc                    |
//! | deploy          | the final stage, plus `CMD`             |

#![deny(missing_docs)]

use std::collections::BTreeSet;
use std::fmt::Write as _;

use autopack_core::plan::{BuildPlan, Cache, CacheType, Command, Layer, Step};
use autopack_core::{Error, Result, APP_DIR};

/// Dockerfile frontend used by generated files.
///
/// Pinned rather than floating on `:1`: `--mount=type=secret,env=` and heredocs
/// both need a known-good frontend, and a pin means a build that worked
/// yesterday still works today.
pub const DEFAULT_SYNTAX: &str = "docker/dockerfile:1.14";

/// Base name of the final stage. A suffix is added if a step already claims it.
const FINAL_STAGE: &str = "autopack-image";

/// Where Debian's `tini` package installs the init binary.
const TINI_PATH: &str = "/usr/bin/tini";

/// True when a start command can safely be `exec`'d.
///
/// `exec` replaces the shell, which is what makes the application tini's
/// direct child. It cannot be applied to a command the shell still has work
/// to do in: a `&&` chain would lose everything after the first command, and
/// a leading `VAR=value` assignment is a syntax error after `exec`.
fn is_simple_command(command: &str) -> bool {
    let has_operators = ["&&", "||", ";", "|", "&", ">", "<", "`", "$("]
        .iter()
        .any(|operator| command.contains(operator));

    // A leading assignment such as `FOO=bar server` must stay a shell command.
    let starts_with_assignment = command
        .split_whitespace()
        .next()
        .is_some_and(|word| word.contains('=') && !word.starts_with('/'));

    !has_operators && !starts_with_assignment
}

/// Rendering options.
#[derive(Debug, Clone)]
pub struct DockerfileOptions {
    /// Frontend image for the `# syntax=` directive.
    pub syntax: String,
    /// Emit a leading comment explaining where the file came from.
    pub header: bool,
}

impl Default for DockerfileOptions {
    fn default() -> Self {
        Self {
            syntax: DEFAULT_SYNTAX.to_string(),
            header: true,
        }
    }
}

/// Render `plan` as a Dockerfile with default options.
pub fn to_dockerfile(plan: &BuildPlan) -> Result<String> {
    to_dockerfile_with(plan, &DockerfileOptions::default())
}

/// Render `plan` as a Dockerfile.
pub fn to_dockerfile_with(plan: &BuildPlan, options: &DockerfileOptions) -> Result<String> {
    plan.validate()?;

    let mut out = String::new();
    let _ = writeln!(out, "# syntax={}", options.syntax);
    if options.header {
        out.push_str(
            "# Generated by autopack. Edits are lost on the next build — change\n\
             # autopack.json or AUTOPACK_* variables instead.\n",
        );
    }

    for step in plan.execution_order()? {
        out.push('\n');
        render_step(&mut out, plan, step)?;
    }

    out.push('\n');
    render_deploy(&mut out, plan, &final_stage_name(plan))?;
    Ok(out)
}

/// The `.dockerignore` matching `plan.exclude`.
///
/// Written next to the Dockerfile as `<name>.dockerignore`, which BuildKit
/// picks up automatically, so nothing is added to the user's repository.
pub fn to_dockerignore(plan: &BuildPlan) -> String {
    let mut out = String::from("# Generated by autopack.\n");
    for path in &plan.exclude {
        out.push_str(path);
        out.push('\n');
    }
    out
}

fn render_step(out: &mut String, plan: &BuildPlan, step: &Step) -> Result<()> {
    let stage = stage_name(&step.name);
    let _ = writeln!(out, "# ---- {} ----", step.name);

    let base = step.inputs.first().ok_or_else(|| {
        Error::InvalidPlan(format!(
            "step `{}` has no inputs, so there is nothing to build it from",
            step.name
        ))
    })?;
    let base_ref = base_reference(base, &step.name)?;
    let _ = writeln!(out, "FROM {base_ref} AS {stage}");
    let _ = writeln!(out, "WORKDIR {APP_DIR}");

    if !step.variables.is_empty() {
        let assignments = step
            .variables
            .iter()
            .map(|(key, value)| format!("{key}={}", quote(value)))
            .collect::<Vec<_>>()
            .join(" \\\n    ");
        let _ = writeln!(out, "ENV {assignments}");
    }

    // Exclusions on the base layer are applied by deleting after the fact:
    // `COPY --exclude` only exists on the labs frontend.
    render_exclusions(out, &base.filter.exclude);

    for input in step.inputs.iter().skip(1) {
        render_overlay(out, input, &step.name)?;
    }

    let mounts = mount_flags(plan, step);
    for command in &step.commands {
        render_command(out, command, &mounts, step)?;
    }

    Ok(())
}

fn render_command(out: &mut String, command: &Command, mounts: &str, step: &Step) -> Result<()> {
    match command {
        Command::Exec(exec) => {
            if let Some(name) = &exec.custom_name {
                let _ = writeln!(out, "# {name}");
            }
            let _ = writeln!(out, "RUN{mounts} {}", exec.cmd);
        }
        Command::Path(path) => {
            let _ = writeln!(out, "ENV PATH=\"{}:$PATH\"", path.path);
        }
        Command::Copy(copy) => match &copy.image {
            Some(image) => {
                let _ = writeln!(out, "COPY --from={image} {} {}", copy.src, copy.dest);
            }
            None => {
                let _ = writeln!(out, "COPY {} {}", copy.src, copy.dest);
            }
        },
        Command::File(file) => {
            let contents = step.assets.get(&file.name).ok_or_else(|| {
                Error::InvalidPlan(format!(
                    "step `{}` writes `{}` from asset `{}`, which is not defined",
                    step.name, file.path, file.name
                ))
            })?;
            let delimiter = heredoc_delimiter(contents);
            let chmod = file
                .mode
                .map(|mode| format!(" --chmod={mode:04o}"))
                .unwrap_or_default();
            // The opening delimiter is quoted so the shell does not expand
            // `$VAR` inside generated config files; the closing one must not be.
            let _ = writeln!(out, "COPY{chmod} <<'{delimiter}' {}", file.path);
            out.push_str(contents);
            if !contents.ends_with('\n') {
                out.push('\n');
            }
            let _ = writeln!(out, "{delimiter}");
        }
    }
    Ok(())
}

/// A final stage name that cannot collide with a step's stage.
///
/// Steps are named by the provider, and one of them is conventionally called
/// `runtime`, so the final stage has to check rather than assume.
fn final_stage_name(plan: &BuildPlan) -> String {
    let taken: BTreeSet<String> = plan
        .steps
        .iter()
        .map(|step| stage_name(&step.name))
        .collect();
    let mut name = FINAL_STAGE.to_string();
    let mut suffix = 1;
    while taken.contains(&name) {
        suffix += 1;
        name = format!("{FINAL_STAGE}-{suffix}");
    }
    name
}

fn render_deploy(out: &mut String, plan: &BuildPlan, final_stage: &str) -> Result<()> {
    let _ = writeln!(out, "# ---- runtime image ----");
    let base = base_reference(&plan.deploy.base, "deploy")?;
    let _ = writeln!(out, "FROM {base} AS {final_stage}");
    let _ = writeln!(out, "WORKDIR {APP_DIR}");

    // Ownership is applied while copying rather than with a later `chown -R`,
    // which would duplicate every copied file into a second layer.
    let chown = plan
        .deploy
        .user
        .as_ref()
        .map(|user| format!(" --chown={}:{}", user.uid, user.gid));

    for input in &plan.deploy.inputs {
        render_overlay_owned(out, input, "deploy", chown.as_deref())?;
    }

    if !plan.deploy.paths.is_empty() {
        let _ = writeln!(out, "ENV PATH=\"{}:$PATH\"", plan.deploy.paths.join(":"));
    }

    for (key, value) in &plan.deploy.variables {
        let _ = writeln!(out, "ENV {key}={}", quote(value));
    }

    if let Some(user) = &plan.deploy.user {
        // The working directory is created by WORKDIR as root; without this the
        // application cannot write to its own directory.
        let _ = writeln!(out, "RUN chown {}:{} {APP_DIR}", user.uid, user.gid);
        let _ = writeln!(out, "USER {}:{}", user.uid, user.gid);
        // Tools that fall back to $HOME need it set and writable; without this
        // Caddy tries /root/.local and npm tries /root/.npm.
        let _ = writeln!(out, "ENV HOME={}", user.home);
    }

    let start = plan
        .deploy
        .start_command
        .as_deref()
        .ok_or(Error::MissingStartCommand)?;

    // tini reaps zombies and forwards signals. `-g` sends them to the whole
    // process group, which covers start commands that stay a shell (pipelines,
    // `&&` chains) instead of exec'ing into the application.
    let _ = writeln!(out, "ENTRYPOINT [\"{TINI_PATH}\", \"-g\", \"--\"]");

    // `sh -c` keeps `$PORT`-style expansion working; `exec` then replaces the
    // shell so the application is tini's direct child rather than sitting
    // behind a shell that does not forward signals.
    let command = if is_simple_command(start) {
        format!("exec {start}")
    } else {
        start.to_string()
    };
    let _ = writeln!(out, "CMD [\"/bin/sh\", \"-c\", {}]", json_string(&command));
    Ok(())
}

/// Emit the `FROM` reference for a layer.
fn base_reference(layer: &Layer, owner: &str) -> Result<String> {
    match (&layer.image, &layer.step, layer.local) {
        (Some(image), _, _) => Ok(image.clone()),
        (_, Some(step), _) => Ok(stage_name(step)),
        (_, _, true) => Err(Error::InvalidPlan(format!(
            "`{owner}` uses the local build context as its base layer; a base must be \
             an image or another step"
        ))),
        _ => Err(Error::InvalidPlan(format!(
            "`{owner}` has an empty base layer"
        ))),
    }
}

/// Emit the `COPY` statements for a non-base input.
fn render_overlay(out: &mut String, layer: &Layer, owner: &str) -> Result<()> {
    render_overlay_owned(out, layer, owner, None)
}

/// Emit the `COPY` statements for a non-base input, optionally reassigning
/// ownership as the files are copied.
fn render_overlay_owned(
    out: &mut String,
    layer: &Layer,
    owner: &str,
    chown: Option<&str>,
) -> Result<()> {
    let chown = chown.unwrap_or("");
    let from = match (&layer.image, &layer.step, layer.local) {
        (Some(image), _, _) => Some(image.clone()),
        (_, Some(step), _) => Some(stage_name(step)),
        (_, _, true) => None,
        _ => {
            return Err(Error::InvalidPlan(format!(
                "`{owner}` has an input with no source"
            )))
        }
    };

    match from {
        // Copying from an image or an earlier stage: include paths are
        // absolute and keep their location in the destination.
        Some(from) => {
            if layer.filter.include.is_empty() {
                let _ = writeln!(out, "COPY{chown} --from={from} / /");
            } else {
                for path in &layer.filter.include {
                    let _ = writeln!(out, "COPY{chown} --from={from} {path} {path}");
                }
            }
        }
        // Copying the build context: paths are relative to the context root
        // and land under the working directory.
        None => {
            if layer.filter.include.is_empty() {
                let _ = writeln!(out, "COPY{chown} . {APP_DIR}");
            } else {
                for path in &layer.filter.include {
                    let destination = if path.ends_with('/') {
                        format!("{APP_DIR}/{}", path.trim_matches('/'))
                    } else {
                        format!("{APP_DIR}/{}", path.trim_start_matches('/'))
                    };
                    let _ = writeln!(out, "COPY{chown} {path} {destination}");
                }
            }
        }
    }

    render_exclusions(out, &layer.filter.exclude);
    Ok(())
}

fn render_exclusions(out: &mut String, exclude: &[String]) {
    if exclude.is_empty() {
        return;
    }
    let paths = exclude
        .iter()
        .map(|path| quote(path))
        .collect::<Vec<_>>()
        .join(" ");
    let _ = writeln!(out, "RUN rm -rf {paths}");
}

/// Cache and secret mount flags shared by every `RUN` in a step.
fn mount_flags(plan: &BuildPlan, step: &Step) -> String {
    let mut flags = String::new();

    for name in &step.caches {
        let Some(cache) = plan.caches.get(name) else {
            continue;
        };
        let sharing = match cache.cache_type {
            CacheType::Shared => "shared",
            CacheType::Locked => "locked",
        };
        // The id keys the cache to this app's directory, so two projects that
        // both cache `/cache/npm` do not fight over one volume.
        let _ = write!(
            flags,
            " --mount=type=cache,id={id},target={target},sharing={sharing}",
            id = cache_id(name, cache),
            target = cache.directory,
        );
    }

    for name in secret_names(plan, step) {
        let _ = write!(
            flags,
            " --mount=type=secret,id={name},env={name},required=false"
        );
    }

    flags
}

/// The secrets a step may read, with `*` expanded to the plan's secret list.
fn secret_names(plan: &BuildPlan, step: &Step) -> Vec<String> {
    if step.uses_all_secrets() {
        return plan.secrets.clone();
    }

    let declared: BTreeSet<&String> = plan.secrets.iter().collect();
    step.secrets
        .iter()
        .filter(|name| declared.contains(name))
        .cloned()
        .collect()
}

fn cache_id(name: &str, cache: &Cache) -> String {
    format!("autopack-{name}-{}", sanitize(&cache.directory))
}

/// A Dockerfile stage name derived from a step name.
fn stage_name(step: &str) -> String {
    format!("autopack-{}", sanitize(step))
}

fn sanitize(value: &str) -> String {
    value
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

/// A heredoc delimiter guaranteed not to appear in `contents`.
fn heredoc_delimiter(contents: &str) -> String {
    let mut delimiter = String::from("AUTOPACK_EOF");
    let mut suffix = 0;
    while contents.contains(&delimiter) {
        suffix += 1;
        delimiter = format!("AUTOPACK_EOF_{suffix}");
    }
    delimiter
}

/// Quote a value for use on an `ENV` line.
fn quote(value: &str) -> String {
    if !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "-_./:@+=".contains(c))
    {
        return value.to_string();
    }
    json_string(value)
}

fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use autopack_core::plan::{Deploy, Filter};
    use autopack_core::{analyze, App, Environment};
    use std::fs;

    fn fixture(files: &[(&str, &str)]) -> (tempfile::TempDir, App) {
        let dir = tempfile::tempdir().unwrap();
        for (path, contents) in files {
            let full = dir.path().join(path);
            fs::create_dir_all(full.parent().unwrap()).unwrap();
            fs::write(full, contents).unwrap();
        }
        let app = App::new(dir.path()).unwrap();
        (dir, app)
    }

    fn dockerfile_for(files: &[(&str, &str)]) -> String {
        let (_dir, app) = fixture(files);
        let analysis = analyze(&app, &Environment::new(), &autopack_providers::registry()).unwrap();
        to_dockerfile(&analysis.plan).unwrap()
    }

    #[test]
    fn renders_a_node_app() {
        let dockerfile = dockerfile_for(&[
            (
                "package.json",
                r#"{"scripts":{"build":"tsc","start":"node dist/index.js"}}"#,
            ),
            ("package-lock.json", "{}"),
        ]);

        assert!(dockerfile.starts_with("# syntax=docker/dockerfile:1.14\n"));
        assert!(dockerfile.contains("FROM debian:bookworm-slim AS autopack-packages"));
        assert!(dockerfile.contains("FROM autopack-packages AS autopack-install"));
        assert!(dockerfile.contains("FROM autopack-install AS autopack-build"));
        assert!(dockerfile.contains("COPY package.json /app/package.json"));
        assert!(dockerfile.contains("COPY . /app"));
        assert!(dockerfile.contains(r#"ENTRYPOINT ["/usr/bin/tini", "-g", "--"]"#));
        assert!(dockerfile.contains(r#"CMD ["/bin/sh", "-c", "exec node dist/index.js"]"#));
    }

    #[test]
    fn cache_mounts_carry_the_sharing_mode() {
        let dockerfile = dockerfile_for(&[
            ("Cargo.toml", "[package]\nname = \"api\"\n"),
            ("src/main.rs", "fn main() {}"),
        ]);
        assert!(dockerfile.contains("--mount=type=cache,id=autopack-cargo-target-app-target,target=/app/target,sharing=locked"));
        assert!(dockerfile.contains("sharing=shared"));
    }

    #[test]
    fn assets_become_heredocs() {
        let dockerfile = dockerfile_for(&[("index.html", "<h1>hi</h1>")]);
        assert!(dockerfile.contains("COPY <<'AUTOPACK_EOF' /app/Caddyfile"));
        assert!(dockerfile.contains("root * /app"));
        assert!(dockerfile.contains("\nAUTOPACK_EOF\n"));
    }

    #[test]
    fn secrets_become_env_mounts() {
        let mut plan = BuildPlan::new();
        plan.secrets = vec!["DATABASE_URL".into()];
        let mut build = Step::new("build");
        build.add_input(Layer::image("alpine"));
        build.add_command(Command::shell("./build.sh"));
        plan.add_step(build);
        plan.deploy = Deploy {
            base: Layer::step("build"),
            start_command: Some("./app".into()),
            ..Default::default()
        };

        let dockerfile = to_dockerfile(&plan).unwrap();
        assert!(dockerfile
            .contains("--mount=type=secret,id=DATABASE_URL,env=DATABASE_URL,required=false"));
    }

    #[test]
    fn a_local_base_layer_is_rejected_with_an_explanation() {
        let mut plan = BuildPlan::new();
        let mut build = Step::new("build");
        build.add_input(Layer::local());
        plan.add_step(build);
        plan.deploy = Deploy {
            base: Layer::step("build"),
            start_command: Some("./app".into()),
            ..Default::default()
        };

        let err = to_dockerfile(&plan).unwrap_err();
        assert!(err.to_string().contains("base must be"), "{err}");
    }

    #[test]
    fn excluded_paths_are_removed_after_copying() {
        let mut plan = BuildPlan::new();
        let mut build = Step::new("build");
        build.add_input(Layer::image("alpine"));
        build.add_input(Layer::local().with_filter(Filter::exclude(["/app/secrets"])));
        plan.add_step(build);
        plan.deploy = Deploy {
            base: Layer::step("build"),
            start_command: Some("./app".into()),
            ..Default::default()
        };

        let dockerfile = to_dockerfile(&plan).unwrap();
        assert!(dockerfile.contains("RUN rm -rf /app/secrets"));
    }

    #[test]
    fn the_final_stage_does_not_collide_with_a_step() {
        let dockerfile = dockerfile_for(&[("index.html", "")]);
        let stage_lines: Vec<&str> = dockerfile
            .lines()
            .filter(|line| line.starts_with("FROM "))
            .collect();
        let mut names: Vec<&str> = stage_lines
            .iter()
            .filter_map(|line| line.rsplit(" AS ").next())
            .collect();
        let total = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(
            names.len(),
            total,
            "duplicate stage names in {stage_lines:?}"
        );
    }

    #[test]
    fn dockerignore_lists_excluded_paths() {
        let (_dir, app) = fixture(&[("index.html", "")]);
        let analysis = analyze(&app, &Environment::new(), &autopack_providers::registry()).unwrap();
        let ignore = to_dockerignore(&analysis.plan);
        assert!(ignore.contains(".git\n"));
    }

    #[test]
    fn go_runtime_image_has_no_toolchain_stage_copy() {
        let dockerfile = dockerfile_for(&[
            ("go.mod", "module example.com/api\n\ngo 1.23\n"),
            ("main.go", "package main\nfunc main() {}\n"),
        ]);
        let runtime = dockerfile
            .split("# ---- runtime image ----")
            .nth(1)
            .unwrap();
        assert!(runtime.contains("--from=autopack-build /app/bin/app /app/bin/app"));
        assert!(!runtime.contains("/mise"));
    }
}
